version: '3.3'
services:
  php:
    image: grafikart/php:1.0.3
    volumes:
      - .:/var/www:delegated
  neo4j:
    image: neo4j:3.5.24-enterprise
    command: "/entrypoint.sh"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/neo"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./downloads/backup/graph.db-backup:/backup
      - ./tools/docker/neo4jentry.sh:/entrypoint.sh
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: grafikart
      POSTGRES_USER: grafikart
      POSTGRES_DB: grafikart
    volumes:
      - ./var:/var/www/var
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./downloads/grafikart:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grafikart_dev
