---
- name: Symfony | Clone
  become: no
  git:
    repo: 'https://github.com/Grafikart/Grafikart.fr.git'
    dest: "{{ root_path }}"
    version: master
- name: Symfony | .env.local"
  become: no
  template:
    src: .env.local.j2
    dest: "{{ root_path }}/.env.local"
- name: Symfony | Composer install
  become: no
  community.general.composer:
    command: install
    working_dir: "{{ root_path }}"
- name: Symfony | Migrate
  become: no
  shell:
    cmd: php bin/console doctrine:migrations:migrate -q
    chdir: "{{ root_path }}"
- include_tasks: typesense.yml
- include_tasks: messenger.yml
- include_tasks: mercure.yml
- name: Symfony | build asset
  become: no
  local_action:
    module: shell
    cmd: yarn run build
    creates: public/assets
- name: Symfony | assets
  become: no
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../../public/assets"
    dest: "{{ root_path }}/public/"
    recursive: yes
    owner: no
    group: no
- name: Symfony | var permission
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "{{ ansible_user }}"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | var permission www-data
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "www-data"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | var permission www-data
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "www-data"
    etype: user
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | dossier uploads
  become: no
  file: state=directory path="{{ root_path }}/public/uploads"
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: www-data
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: www-data
    etype: user
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: "{{ ansible_user }}"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
