---
- name: Messenger | Service
  become: no
  template:
    src: "messenger.service.j2"
    dest: "~/.config/systemd/user/{{ domain }}.messenger.service"
- name: Messenger | Activation du Service
  become: no
  systemd:
    scope: user
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ domain }}.messenger"
